---
title: "Project 3"
author: "Kristin Calvert"
date: "7/15/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
library(tidyverse)
library(knitr)
library(DT)
```

## Project 3 

```{r data_ingest}

#read in data
data_by_library <- read_csv("libraries.csv")

data_by_state <- read_csv("states.csv")

#convert columns to factors
data_by_state$State <- as.factor(data_by_state$State)
data_by_state$`Region Code` <- as.factor(data_by_state$`Region Code`)

#create a new column for total number of libraries
data_by_state$`Total Libraries` <- data_by_state$`Central Libraries`+data_by_state$`Branch Libraries`

#subset data for southeast region
data_by_region_se <- data_by_state %>% filter(`Region Code` == "5")
```

## Data Exploration

```{r data_summary}
#Summarize by region
regional_summary <- data_by_state %>% group_by(`Region Code`) %>% summarise("Average Service Population" = mean(`Service Population`), "Average Service Population per Library" = mean(`Service Population`)/(sum(`Central Libraries`)+sum(`Branch Libraries`)), "Average Library Employees per 10,000 People" = mean(Employees)/sum(`Service Population`)*10000, "Average Collections Spending per 10,000 People" = mean(`Total Collection Expenditures`)/sum(`Service Population`)*10000, "Total Visits" = sum(`Library Visits`))


#Create groupings of columns
Staffing <- c("MLS Librarians", "Librarians", "Employees", "Total Staff")
Finances <- c("Total Staff Expenditures", "Total Operating Expenditures", "Print Collection Expenditures",
"Digital Collection Expenditures", "Other Collection Expenditures", "Total Collection Expenditures")
Collections <- c("Print Collection", "Digital Collection", "Audio Collection", "Downloadable Audio", "Physical Video", "Downloadable Video", "State Licensed Databases", "Total Licensed Databases", "Print Subscriptions")

#Function to create a summary table based on grouped columns
subset_data <- function(x){
  subset <- data_by_state %>% select(x)
  kable(round(apply(subset, 2, summary), 2), caption = paste("State-Level Summary Statistics for", deparse(substitute(x))))
}

subset_data(Staffing)
subset_data(Finances)
subset_data(Collections)

#Scatter plot

g <- ggplot(data = data_by_state, aes(x = `Circulation Transactions`, y = `Service Population`, group = `Region Code`))
g + geom_point(aes(color = `Library Visits`))

gp <- ggplot(data = data_by_state, aes(x = `Total Staff Expenditures`, y = `Circulation Transactions`))
gp + geom_point(aes(color = `Region Code`))



```

```{r box_and_bar_plots}
#Box plot function for operating costs by region

##plot_costs_by_region <- function(region, cost){
  
    #Switch from string to code for region
#  region <- switch(input$region, "New England (CT ME MA NH RI VT)" = "1" , "Mid East (DE DC MD NH NY PA)" = "2", "Great Lakes(IL IN MI OH WI" = "3", "Plains (IA KS MN MO NE ND SD" ="4", "Southeast (AL AR FL GA KY L MS NC SC TN VA WV" = "5", "Southwest (AZ NM OK TX)" = "6", "Rocky Mountains (CO ID MT UT WY)" = "7", "Far West (AK CA HI NV OR WA)" = "8")  ##Switch to dynamic input$region
  
    #Function to subset data by selected region
  subset_by_region <- function(region){
  data_by_region <- data_by_state %>% filter(`Region Code` == region) 
  }
  
    #Bar chart of selected cost variable by selected region
  ggplot(data = data_by_region_se, aes(x = `State`, y = `Total Operating Expenditures`/`State Population`)) + ##switch to input$cost_type and input$region
    geom_bar(stat = "Identity") + 
    ggtitle("Per Capita Public Library Operating Costs for Southeast Region (US).") + ##Switch to dynamic title
    ylab("Dollars Spent per Capita")
##}
```

```{r PCA}

#Create the PCs. Not to be adjustable by input
PCs <- prcomp(select(data_by_state, `Service Population`, `Total Libraries`, `Total Staff`, `Local Government Operating Revenue`, `Total Operating Revenue`, `Total Staff Expenditures`, `Print Collection Expenditures`, `Total Collection Expenditures`, `Total Operating Expenditures`, `Print Collection`, `Audio Collection`, `Physical Video`, `Print Subscriptions`, `Hours Open`, `Library Visits`, `Circulation Transactions`, `Library Programs`, `Library Programs`, `Public Internet Computers`, `Internet Computer Use`), center = TRUE, scale = TRUE)

#Create the scree plot
screeplot(PCs, type = "lines")

#Create plots to show proportion of variance and cummulative variance by PC
par(mfrow = c(1, 2))
plot(PCs$sdev^2/sum(PCs$sdev^2), xlab = "Principal Component", 
         ylab = "Proportion of Variance Explained", ylim = c(0, 1), type = 'b')
plot(cumsum(PCs$sdev^2/sum(PCs$sdev^2)), xlab = "Principal Component", 
ylab = "Cum. Prop of Variance Explained", ylim = c(0, 1), type = 'b')

#Create Biplot
##Must add user input to view PCs
biplot(PCs, xlabs = rep(".", nrow(data_by_state)), choices = c(2,3), cex = .6)

##Must add dynamic table print for PCs selected in the biplot
kable(PCs$rotation[,c("PC1","PC2")])

```

```{r modeling}


```

