library(plotly)
library(shiny)
library(tidyverse)
library(knitr)
library(DT)
library(caret)
library(leaflet)
library(kableExtra)
library(ggfortify)
library(ciTools)
library(RColorBrewer)
library(rattle)
library(tree)

options(knitr.table.format = "html") 